import SchoolsList from '@src/views/School/List'

const badges = {
  true: { label: 'Active', className: 'badge-green' },
  false: { label: 'Inactive', className: 'badge-yellow' },
  undefined: { label: 'Unknown', className: 'badge-gray' },
}

const buttonsKeys = {
  true: { label: 'Activate', className: 'btn-green' },
  false: { label: 'Deactivate', className: 'btn-orange' },
  undefined: { label: 'Unknown', className: 'btn-gray' },
}

const accessorkeys = {
  adminList: {
    id: 'id',
    username: 'username',
    email: 'email',
    phoneNumber: 'phone_number',
    adminRole: 'admin_role',
    isActive: 'is_active',
    actions: 'Actions',
  },
  subscriptionPlans: {
    id: 'id',
    planName: 'plan_name',
    planType: 'plan_type',
    pricingModel: 'pricing_model',
    price: 'price',
    kids: 'kids',
    isActive: 'is_active',
    actions: 'Actions',
  },
  schoolSubscriptionPlans: {
    id: 'id',
    planName: 'plan_name',
    price: 'price',
    startDate: 'start_date',
    endDate: 'end_date',
    subscriptionStatus: 'subscription_status',
  },
  payments: {
    id: 'id',
    paymentId: '_id',
    amount: 'amount',
    paymentMethod: 'payment_method',
    paymentStatus: 'payment_status',
    paymentDate: 'payment_date',
    actions: 'Actions',
  },
  schoolsList: {
    id: 'id',
    schoolName: 'school_name',
    email: 'email',
    contactNumber: 'contact_number',
    city: 'city',
    state: 'state',
    actions: 'Actions',
  },
  studentsList: {
    id: 'id',
    name: 'username',
    email: 'email',
    phoneNumber: 'phone_number',
    grade: 'grade',
    parentName: 'parent_name',
    schoolName: 'school_name',
    actions: 'Actions',
  },
  driversList: {
    id: 'id',
    name: 'name',
    email: 'email',
    phoneNumber: 'phone_number',
    isActive: 'is_active',
    actions: 'Actions',
  },
  parentsList: {
    id: 'id',
    name: 'name',
    email: 'email',
    phoneNumber: 'phone_number',
    isActive: 'is_active',
    actions: 'Actions',
  },
  tripsList: {
    id: 'id',
    tripId: '_id',
    tripType: 'trip_type',
    tripStatus: 'trip_status',
    tripDate: 'trip_date',
    totalDistance: 'total_distance',
  },
  liveTracking: {
    id: 'id',
    tripId: '_id',
    tripType: 'trip_type',
    startTime: 'start_time',
    totalDistance: 'total_distance',
    actions: 'Actions',
  },
  id: 'id',
  username: 'username',
  email: 'email',
  phoneNumber: 'phone_number',
  adminRole: 'admin_role',
  isActive: 'is_active',
  actions: 'Actions',
  name: 'name',
  contactNumber: 'contact_number',
  userType: 'user_type',
  schoolName: 'school_name',
  address: 'address',
  city: 'city',
  state: 'state',
  // Student
  grade: 'grade',
  parentName: 'parent_name',
  // Trip
  tripId: '_id',
  tripType: 'trip_type',
  tripStatus: 'trip_status',
  tripDate: 'trip_date',
  totalDistance: 'total_distance',
  // Assignment
  assignmentStatus: 'assignment_status',
  studentId: 'student_id',
  driverUniqueId: 'driver_unique_id',
  assignmentId: '_id',
  driverName: 'driver_name',
  // Subscription
  planName: 'plan_name',
  plan_id: 'plan_id',
  parent_id: 'parent_id',
  planType: 'plan_type',
  amount: 'amount',
  startDate: 'start_date',
  endDate: 'end_date',
  subscriptionStatus: 'status',
  pricingModel: 'pricing_model',
  basePrice: 'base_price',
  price: 'price',
  kids: 'kids',
  calculated_price: 'calculated_price',
  subscription_status: 'subscription_status',

  // Redemption Codes
  code: 'code',
  codeStatus: 'status',
  // Role
  roleName: 'name',
  description: 'description',
  // Audit Log
  action: 'action',
  resource: 'resource',
  timestamp: 'created_at',
  // Notification
  title: 'title',
  message: 'message',
  isRead: 'is_read',
  // Rating
  rating: 'rating',
  review: 'review',
  // Payment
  paymentId: '_id',
  paymentType: 'payment_type',
  paymentMethod: 'payment_method',
  paymentStatus: 'payment_status',
  transactionId: 'transaction_id',
  paymentDate: 'payment_date',
  currency: 'currency',
}

const headerKeys = {
  adminList: {
    id: 'ID',
    username: 'Name',
    email: 'Email',
    phoneNumber: 'Phone Number',
    adminRole: 'Role',
    isActive: 'Status',
    actions: 'Actions',
  },
  subscriptionPlans: {
    id: 'ID',
    planName: 'Plan Name',
    planType: 'Plan Type',
    pricingModel: 'Pricing Model',
    price: 'Price',
    kids: 'Kids',
    isActive: 'Status',
    actions: 'Actions',
  },
  schoolSubscriptionPlans: {
    id: 'ID',
    planName: 'Plan Name',
    price: 'Price',
    startDate: 'Start Date',
    endDate: 'End Date',
    subscriptionStatus: 'Status',
  },
  payments: {
    id: 'ID',
    paymentId: 'Payment ID',
    amount: 'Amount',
    paymentMethod: 'Payment Method',
    paymentStatus: 'Payment Status',
    paymentDate: 'Payment Date',
    actions: 'Actions',
  },
  schoolsList: {
    id: 'ID',
    schoolName: 'School Name',
    email: 'Email',
    contactNumber: 'Contact Number',
    city: 'City',
    state: 'State',
    actions: 'Actions',
  },
  studentsList: {
    id: 'ID',
    name: 'Name',
    email: 'Email',
    phoneNumber: 'Phone Number',
    grade: 'Grade',
    parentName: 'Parent',
    schoolName: 'School Name',
    actions: 'Actions',
  },
  driversList: {
    id: 'ID',
    name: 'Name',
    email: 'Email',
    phoneNumber: 'Phone Number',
    isActive: 'Status',
    actions: 'Actions',
  },
  parentsList: {
    id: 'ID',
    name: 'Name',
    email: 'Email',
    phoneNumber: 'Phone Number',
    isActive: 'Status',
    actions: 'Actions',
  },
  tripsList: {
    id: 'ID',
    tripId: 'Trip ID',
    tripType: 'Type',
    tripStatus: 'Status',
    tripDate: 'Date',
    totalDistance: 'Total Distance',
  },
  liveTracking: {
    id: 'ID',
    tripId: 'Trip ID',
    tripType: 'Type',
    startTime: 'Started At',
    totalDistance: 'Total Distance',
    actions: 'Actions',
  },
  id: 'ID',
  username: 'Name',
  phoneNumber: 'Phone Number',
  adminRole: 'Role',
  isActive: 'Active',
  actions: 'Actions',
  Name: 'Name',
  email: 'Email',
  contactNumber: 'Contact Number',
  userType: 'User Type',
  schoolName: 'School Name',
  address: 'Address',
  city: 'City',
  state: 'State',
  // Student
  grade: 'Grade',
  parentName: 'Parent',
  // Trip
  tripId: 'Trip ID',
  tripType: 'Type',
  tripStatus: 'Status',
  tripDate: 'Date',
  totalDistance: 'Total Distance',
  // Assignment
  assignmentStatus: 'Status',
  studentId: 'Student',
  driverName: 'Driver',
  assignmentId: 'Assignment ID',
  driverUniqueId: 'Driver Unique ID',
  // Subscription
  planName: 'Plan',
  planType: 'Plan Type',
  amount: 'Amount',
  startDate: 'Start Date',
  endDate: 'End Date',
  subscriptionStatus: 'Status',
  pricingModel: 'Pricing Model',
  basePrice: 'Base Price',
  price: 'Price',
  kids: 'Kids',
  // Redemption Codes
  code: 'Code',
  codeStatus: 'Status',
  // Role
  roleName: 'Role Name',
  description: 'Description',
  // Audit Log
  action: 'Action',
  resource: 'Resource',
  timestamp: 'Timestamp',
  // Notification
  title: 'Title',
  message: 'Message',
  isRead: 'Read',
  // Rating
  rating: 'Rating',
  review: 'Review',
  // Payment
  paymentId: 'Payment ID',
  paymentType: 'Type',
  paymentMethod: 'Method',
  paymentStatus: 'Status',
  transactionId: 'Transaction ID',
  paymentDate: 'Payment Date',
  currency: 'Currency',
}

export { badges, accessorkeys, headerKeys, buttonsKeys }
