import { AssignmentStatus, TripStatus } from './enums'

const accessorkeys = {
  // ── Admin ──────────────────────────────────────────────
  adminList: {
    id: 'id',
    username: 'username',
    email: 'email',
    phoneNumber: 'phone_number',
    adminRole: 'admin_role',
    isActive: 'is_active',
    actions: 'Actions',
  },
  // ── Schools ────────────────────────────────────────────
  schoolsList: {
    id: 'id',
    schoolName: 'school_name',
    email: 'email',
    contactNumber: 'contact_number',
    city: 'city',
    state: 'state',
    actions: 'Actions',
  },
  schoolAdminsList: {
    id: 'id',
    email: 'email',
    phoneNumber: 'phone_number',
    isActive: 'is_active',
    actions: 'Actions',
  },
  schoolDriversList: {
    id: 'id',
    username: 'username',
    email: 'email',
    phoneNumber: 'phone_number',
    approvalStatus: 'approval_status',
    actions: 'Actions',
  },
  schoolDetails: {
    id: 'id',
    name: 'name',
    email: 'email',
    phoneNumber: 'phone_number',
    approvalStatus: 'approval_status',
    isActive: 'is_active',
    actions: 'Actions',
  },
  // ── Users ──────────────────────────────────────────────
  studentsList: {
    id: 'id',
    name: 'username',
    email: 'email',
    phoneNumber: 'phone_number',
    grade: 'grade',
    parentName: 'parent_name',
    schoolName: 'school_name',
    actions: 'Actions',
  },
  schoolStudentsList: {
    id: 'id',
    name: 'username',
    grade: 'grade',
    parentName: 'parent_name',
    phoneNumber: 'phone_number',
    assignedDriver: 'assigned_driver',
    actions: 'Actions',
  },
  driversList: {
    id: 'id',
    name: 'name',
    email: 'email',
    phoneNumber: 'phone_number',
    isActive: 'is_active',
    actions: 'Actions',
  },
  driverDocuments: {
    name: 'name',
    number: 'number',
    action: 'action',
  },
  parentsList: {
    id: 'id',
    name: 'name',
    email: 'email',
    phoneNumber: 'phone_number',
    isActive: 'is_active',
    actions: 'Actions',
  },
  parentDetails: {
    id: 'id',
    studentName: 'student_name',
    class: 'class',
    schoolId: 'school_id',
    planName: 'plan_name',
    planType: 'plan_type',
    status: 'status',
    startDate: 'start_date',
    endDate: 'end_date',
    amount: 'amount',
    paymentType: 'payment_type',
    paymentMethod: 'payment_method',
    paymentStatus: 'payment_status',
    paymentDate: 'payment_date',
  },
  // ── Trips ──────────────────────────────────────────────
  tripsList: {
    id: 'id',
    tripId: '_id',
    tripType: 'trip_type',
    tripStatus: 'trip_status',
    tripDate: 'trip_date',
    totalDistance: 'total_distance',
  },
  liveTracking: {
    id: 'id',
    tripId: '_id',
    tripType: 'trip_type',
    startTime: 'start_time',
    totalDistance: 'total_distance',
    actions: 'Actions',
  },
  tripDetails: {
    id: 'id',
    name: 'name',
    pickupStatus: 'pickup_status',
    dropStatus: 'drop_status',
    lat: 'lat',
    lng: 'lng',
    timestamp: 'timestamp',
  },
  // ── Assignments ────────────────────────────────────────
  schoolAssignmentsList: {
    id: 'id',
    driverName: 'driver_name',
    schoolName: 'school_name',
    assignmentStatus: 'status',
    createdAt: 'created_at',
    actions: 'Actions',
  },
  driverStudentList: {
    id: 'id',
    assignmentId: '_id',
    driverUniqueId: 'driver_unique_id',
    studentId: 'student_id',
    assignmentStatus: 'assignment_status',
    createdAt: 'created_at',
    actions: 'Actions',
  },
  // ── Billing ────────────────────────────────────────────
  subscriptionPlans: {
    id: 'id',
    planName: 'plan_name',
    planType: 'plan_type',
    pricingModel: 'pricing_model',
    price: 'price',
    kids: 'kids',
    isActive: 'is_active',
    actions: 'Actions',
  },
  schoolSubscriptionPlans: {
    id: 'id',
    planName: 'plan_name',
    price: 'price',
    startDate: 'start_date',
    endDate: 'end_date',
    subscriptionStatus: 'subscription_status',
  },
  parentSubscriptionsList: {
    id: 'id',
    planId: 'plan_id',
    parentId: 'parent_id',
    subscriptionStatus: 'subscription_status',
    amount: 'calculated_price',
    startDate: 'start_date',
    endDate: 'end_date',
    actions: 'Actions',
  },
  redemptionCodesList: {
    id: 'id',
    code: 'code',
    codeStatus: 'status',
    studentName: 'student_name',
    redeemedAt: 'redeemed_at',
  },
  // ── Payments ───────────────────────────────────────────
  payments: {
    id: 'id',
    paymentId: '_id',
    amount: 'amount',
    paymentMethod: 'payment_method',
    paymentStatus: 'payment_status',
    paymentDate: 'payment_date',
    actions: 'Actions',
  },
  // ── Roles ──────────────────────────────────────────────
  rolesList: {
    id: 'id',
    roleName: 'name',
    description: 'description',
    permissions: 'permissions',
    isSystem: 'is_system',
    actions: 'Actions',
  },
  // ── Audit Logs ─────────────────────────────────────────
  auditLogsList: {
    id: 'id',
    userName: 'user_name',
    userRole: 'user_role',
    action: 'action',
    resource: 'resource',
    timestamp: 'created_at',
    actions: 'Actions',
  },
  // ── Notifications ──────────────────────────────────────
  notificationsList: {
    id: 'id',
    title: 'title',
    message: 'message',
    isRead: 'is_read',
    createdAt: 'created_at',
    actions: 'Actions',
  },
  // ── Ratings & Reviews ──────────────────────────────────
  ratingsReviewsList: {
    id: 'id',
    driverName: 'driver_name',
    parentName: 'parent_name',
    rating: 'rating',
    review: 'review',
    createdAt: 'created_at',
  },
  // ── Community ──────────────────────────────────────────
  communityList: {
    id: 'id',
    content: 'content',
    author: 'author',
    isAnonymous: 'is_anonymous',
    isVisible: 'is_visible',
    isPinned: 'is_pinned',
    createdAt: 'created_at',
    actions: 'Actions',
  },
  // ── Events ─────────────────────────────────────────────
  eventsList: {
    id: 'id',
    title: 'title',
    eventType: 'event_type',
    eventDate: 'event_date',
    audienceScope: 'audience_scope',
    requiresRsvp: 'requires_rsvp',
    actions: 'Actions',
  },
  eventRSVPsList: {
    id: 'id',
    eventTitle: 'event_title',
    parentName: 'parent_name',
    studentName: 'student_name',
    rsvpStatus: 'rsvp_status',
    respondedAt: 'responded_at',
    actions: 'Actions',
  },
  // ── Support ────────────────────────────────────────────
  supportList: {
    id: 'id',
    subject: 'subject',
    userName: 'user_name',
    priority: 'priority',
    status: 'status',
    createdAt: 'created_at',
    actions: 'Actions',
  },
  // ── Ads ────────────────────────────────────────────────
  adsList: {
    id: 'id',
    title: 'title',
    adType: 'ad_type',
    targetAudience: 'target_audience',
    isActive: 'is_active',
    impressions: 'impressions',
    clicks: 'clicks',
    actions: 'Actions',
  },
}

const headerKeys = {
  // ── Admin ──────────────────────────────────────────────
  adminList: {
    id: 'ID',
    username: 'Name',
    email: 'Email',
    phoneNumber: 'Phone Number',
    adminRole: 'Role',
    isActive: 'Status',
    actions: 'Actions',
  },
  // ── Schools ────────────────────────────────────────────
  schoolsList: {
    id: 'ID',
    schoolName: 'School Name',
    email: 'Email',
    contactNumber: 'Contact Number',
    city: 'City',
    state: 'State',
    actions: 'Actions',
  },
  schoolAdminsList: {
    id: 'ID',
    email: 'Email',
    phoneNumber: 'Phone Number',
    isActive: 'Status',
    actions: 'Actions',
  },
  schoolDriversList: {
    id: 'ID',
    username: 'Name',
    email: 'Email',
    phoneNumber: 'Phone Number',
    approvalStatus: 'Approval Status',
    actions: 'Actions',
  },
  schoolDetails: {
    id: 'ID',
    name: 'Name',
    email: 'Email',
    phoneNumber: 'Phone',
    approvalStatus: 'Approval',
    isActive: 'Status',
    actions: 'Actions',
  },
  // ── Users ──────────────────────────────────────────────
  studentsList: {
    id: 'ID',
    name: 'Name',
    email: 'Email',
    phoneNumber: 'Phone Number',
    grade: 'Grade',
    parentName: 'Parent',
    schoolName: 'School Name',
    actions: 'Actions',
  },
  schoolStudentsList: {
    id: 'ID',
    name: 'Name',
    grade: 'Grade',
    parentName: 'Parent',
    phoneNumber: 'Parent Phone',
    assignedDriver: 'Assigned Driver',
    actions: 'Actions',
  },
  driversList: {
    id: 'ID',
    name: 'Name',
    email: 'Email',
    phoneNumber: 'Phone Number',
    isActive: 'Status',
    actions: 'Actions',
  },
  driverDocuments: {
    name: 'Name',
    number: 'Number',
    action: 'Action',
  },
  parentsList: {
    id: 'ID',
    name: 'Name',
    email: 'Email',
    phoneNumber: 'Phone Number',
    isActive: 'Status',
    actions: 'Actions',
  },
  parentDetails: {
    id: 'ID',
    studentName: 'Name',
    class: 'Class',
    schoolId: 'School ID',
    planName: 'Plan',
    planType: 'Type',
    status: 'Status',
    startDate: 'Start Date',
    endDate: 'End Date',
    amount: 'Amount',
    paymentType: 'Type',
    paymentMethod: 'Method',
    paymentStatus: 'Status',
    paymentDate: 'Date',
  },
  // ── Trips ──────────────────────────────────────────────
  tripsList: {
    id: 'ID',
    tripId: 'Trip ID',
    tripType: 'Type',
    tripStatus: 'Status',
    tripDate: 'Date',
    totalDistance: 'Total Distance',
  },
  liveTracking: {
    id: 'ID',
    tripId: 'Trip ID',
    tripType: 'Type',
    startTime: 'Started At',
    totalDistance: 'Total Distance',
    actions: 'Actions',
  },
  tripDetails: {
    id: 'ID',
    name: 'Student Name',
    pickupStatus: 'Pickup Status',
    dropStatus: 'Drop Status',
    lat: 'Latitude',
    lng: 'Longitude',
    timestamp: 'Time',
  },
  // ── Assignments ────────────────────────────────────────
  schoolAssignmentsList: {
    id: 'ID',
    driverName: 'Driver',
    schoolName: 'School',
    assignmentStatus: 'Status',
    createdAt: 'Created',
    actions: 'Actions',
  },
  driverStudentList: {
    id: 'ID',
    assignmentId: 'Assignment ID',
    driverUniqueId: 'Driver Unique ID',
    studentId: 'Student',
    assignmentStatus: 'Status',
    createdAt: 'Created',
    actions: 'Actions',
  },
  // ── Billing ────────────────────────────────────────────
  subscriptionPlans: {
    id: 'ID',
    planName: 'Plan Name',
    planType: 'Plan Type',
    pricingModel: 'Pricing Model',
    price: 'Price',
    kids: 'Kids',
    isActive: 'Status',
    actions: 'Actions',
  },
  schoolSubscriptionPlans: {
    id: 'ID',
    planName: 'Plan Name',
    price: 'Price',
    startDate: 'Start Date',
    endDate: 'End Date',
    subscriptionStatus: 'Status',
  },
  parentSubscriptionsList: {
    id: 'ID',
    planId: 'Plan',
    parentId: 'Parent',
    subscriptionStatus: 'Status',
    amount: 'Amount',
    startDate: 'Start Date',
    endDate: 'End Date',
    actions: 'Actions',
  },
  redemptionCodesList: {
    id: 'ID',
    code: 'Code',
    codeStatus: 'Status',
    studentName: 'Assigned Student',
    redeemedAt: 'Redeemed At',
  },
  // ── Payments ───────────────────────────────────────────
  payments: {
    id: 'ID',
    paymentId: 'Payment ID',
    amount: 'Amount',
    paymentMethod: 'Payment Method',
    paymentStatus: 'Payment Status',
    paymentDate: 'Payment Date',
    actions: 'Actions',
  },
  // ── Roles ──────────────────────────────────────────────
  rolesList: {
    id: 'ID',
    roleName: 'Role Name',
    description: 'Description',
    permissions: 'Permissions',
    isSystem: 'System Role',
    actions: 'Actions',
  },
  // ── Audit Logs ─────────────────────────────────────────
  auditLogsList: {
    id: 'ID',
    userName: 'User',
    userRole: 'Role',
    action: 'Action',
    resource: 'Resource',
    timestamp: 'Timestamp',
    actions: 'Actions',
  },
  // ── Notifications ──────────────────────────────────────
  notificationsList: {
    id: 'ID',
    title: 'Title',
    message: 'Message',
    isRead: 'Read',
    createdAt: 'Date',
    actions: 'Actions',
  },
  // ── Ratings & Reviews ──────────────────────────────────
  ratingsReviewsList: {
    id: 'ID',
    driverName: 'Driver',
    parentName: 'Parent',
    rating: 'Rating',
    review: 'Review',
    createdAt: 'Date',
  },
  // ── Community ──────────────────────────────────────────
  communityList: {
    id: 'ID',
    content: 'Post Content',
    author: 'Author',
    isAnonymous: 'Anonymous',
    isVisible: 'Visible',
    isPinned: 'Pinned',
    createdAt: 'Date',
    actions: 'Actions',
  },
  // ── Events ─────────────────────────────────────────────
  eventsList: {
    id: 'ID',
    title: 'Event Title',
    eventType: 'Type',
    eventDate: 'Date',
    audienceScope: 'Audience',
    requiresRsvp: 'RSVP',
    actions: 'Actions',
  },
  eventRSVPsList: {
    id: 'ID',
    eventTitle: 'Event',
    parentName: 'Parent',
    studentName: 'Student',
    rsvpStatus: 'Response',
    respondedAt: 'Responded At',
    actions: 'Actions',
  },
  // ── Support ────────────────────────────────────────────
  supportList: {
    id: 'ID',
    subject: 'Subject',
    userName: 'Raised By',
    priority: 'Priority',
    status: 'Status',
    createdAt: 'Date',
    actions: 'Actions',
  },
  // ── Ads ────────────────────────────────────────────────
  adsList: {
    id: 'ID',
    title: 'Title',
    adType: 'Type',
    targetAudience: 'Target Audience',
    isActive: 'Status',
    impressions: 'Impressions',
    clicks: 'Clicks',
    actions: 'Actions',
  },
}

// ── Badge Maps ─────────────────────────────────────────────────────────────

// Centralized className definitions (single source of truth for colors)
const badgeClassNames = {
  success: 'badge-green',
  warning: 'badge-yellow',
  error: 'badge-red',
  info: 'badge-blue',
  secondary: 'badge-gray',
  accent: 'badge-purple',
  highlight: 'badge-orange',
  teal: 'badge-teal',
}

// Centralized label definitions (single source of truth for labels)
const badgeLabels = {
  activate: 'Activate',
  deactivate: 'Deactivate',
  active: 'Active',
  inactive: 'Inactive',
  pending: 'Pending',
  approved: 'Approved',
  rejected: 'Rejected',
  scheduled: 'Scheduled',
  started: 'Started',
  in_progress: 'In Progress',
  completed: 'Completed',
  cancelled: 'Cancelled',
  refunded: 'Refunded',
  failed: 'Failed',
  parent_requested: 'Parent Requested',
  expired: 'Expired',
  picked_up: 'Picked Up',
  dropped: 'Dropped',
  missed: 'Missed',
  low: 'Low',
  medium: 'Medium',
  high: 'High',
  open: 'Open',
  resolved: 'Resolved',
  closed: 'Closed',
  sports: 'Sports',
  parent_meeting: 'Parent Meeting',
  cultural: 'Cultural',
  holiday: 'Holiday',
  festival: 'Festival',
  exam: 'Exam',
  excursion: 'Excursion',
  general: 'General',
  attending: 'Attending',
  not_attending: 'Not Attending',
  maybe: 'Maybe',
  available: 'Available',
  redeemed: 'Redeemed',
  unknown: 'Unknown',
}

// combined badge maps - single level
const badgeMaps = {
  true: { label: badgeLabels.activate, className: badgeClassNames.success },
  false: { label: badgeLabels.deactivate, className: badgeClassNames.warning },
  active: {
    label: badgeLabels.active,
    className: badgeClassNames.success,
  },
  inactive: {
    label: badgeLabels.inactive,
    className: badgeClassNames.warning,
  },
  pending: {
    label: badgeLabels.pending,
    className: badgeClassNames.warning,
  },
  approved: { label: badgeLabels.approved, className: badgeClassNames.success },
  rejected: {
    label: badgeLabels.rejected,
    className: badgeClassNames.error,
  },
  scheduled: {
    label: badgeLabels.scheduled,
    className: badgeClassNames.warning,
  },
  started: { label: badgeLabels.started, className: badgeClassNames.info },
  in_progress: {
    label: badgeLabels.in_progress,
    className: badgeClassNames.info,
  },
  completed: {
    label: badgeLabels.completed,
    className: badgeClassNames.success,
  },
  cancelled: {
    label: badgeLabels.cancelled,
    className: badgeClassNames.warning,
  },
  refunded: { label: badgeLabels.refunded, className: badgeClassNames.info },
  failed: { label: badgeLabels.failed, className: badgeClassNames.error },
  parent_requested: {
    label: badgeLabels.parent_requested,
    className: badgeClassNames.accent,
  },
  expired: { label: badgeLabels.expired, className: badgeClassNames.error },
  picked_up: {
    label: badgeLabels.picked_up,
    className: badgeClassNames.success,
  },
  dropped: { label: badgeLabels.dropped, className: badgeClassNames.success },
  missed: { label: badgeLabels.missed, className: badgeClassNames.error },
  low: { label: badgeLabels.low, className: badgeClassNames.secondary },
  medium: { label: badgeLabels.medium, className: badgeClassNames.warning },
  high: { label: badgeLabels.high, className: badgeClassNames.error },
  open: { label: badgeLabels.open, className: badgeClassNames.info },
  resolved: { label: badgeLabels.resolved, className: badgeClassNames.success },
  closed: { label: badgeLabels.closed, className: badgeClassNames.secondary },
  sports: { label: badgeLabels.sports, className: badgeClassNames.info },
  parent_meeting: {
    label: badgeLabels.parent_meeting,
    className: badgeClassNames.accent,
  },
  cultural: { label: badgeLabels.cultural, className: badgeClassNames.warning },
  holiday: { label: badgeLabels.holiday, className: badgeClassNames.success },
  festival: {
    label: badgeLabels.festival,
    className: badgeClassNames.highlight,
  },
  exam: { label: badgeLabels.exam, className: badgeClassNames.error },
  excursion: { label: badgeLabels.excursion, className: badgeClassNames.teal },
  general: { label: badgeLabels.general, className: badgeClassNames.secondary },
  attending: {
    label: badgeLabels.attending,
    className: badgeClassNames.success,
  },
  not_attending: {
    label: badgeLabels.not_attending,
    className: badgeClassNames.error,
  },
  maybe: { label: badgeLabels.maybe, className: badgeClassNames.warning },
  available: {
    label: badgeLabels.available,
    className: badgeClassNames.success,
  },
  redeemed: {
    label: badgeLabels.redeemed,
    className: badgeClassNames.secondary,
  },
  undefined: {
    label: badgeLabels.unknown,
    className: badgeClassNames.secondary,
  },
  monthly: {
    label: 'Monthly',
    className: badgeClassNames.info,
  },
  quarterly: {
    label: 'Quarterly',
    className: badgeClassNames.accent,
  },
  yearly: {
    label: 'Yearly',
    className: badgeClassNames.success,
  },
  anonymous: {
    label: 'Yes',
    className: badgeClassNames.secondary,
  },
  public: {
    label: 'No',
    className: badgeClassNames.info,
  },
  visible: {
    label: 'Visible',
    className: badgeClassNames.success,
  },
  hidden: {
    label: 'Hidden',
    className: badgeClassNames.error,
  },
  pinned: {
    label: 'Pinned',
    className: badgeClassNames.highlight,
  },
  not_pinned: {
    label: 'No',
    className: badgeClassNames.secondary,
  },
  required: {
    label: 'Required',
    className: badgeClassNames.info,
  },
  not_required: {
    label: 'No',
    className: badgeClassNames.secondary,
  },
  read: {
    label: 'Read',
    className: badgeClassNames.secondary,
  },
  unread: {
    label: 'Unread',
    className: badgeClassNames.warning,
  },
}

export { accessorkeys, headerKeys, badgeClassNames, badgeLabels, badgeMaps }
