const accessorkeys = {
  // ── Admin Portal Users ─────────────────────────────────
  adminList: {
    id: 'id',
    username: 'username',
    email: 'email',
    phoneNumber: 'phone_number',
    adminRole: 'admin_role',
    isActive: 'is_active',
    lastLogin: 'last_login',
    createdAt: 'created_at',
    actions: 'Actions',
  },
  // ── Schools ────────────────────────────────────────────
  schoolsList: {
    id: 'id',
    schoolName: 'school_name',
    cityState: 'city',
    contact: 'contact_number',
    email: 'email',
    driverCount: 'driver_count',
    studentCount: 'student_count',
    subscriptionStatus: 'subscription_status',
    createdAt: 'created_at',
    actions: 'Actions',
  },
  schoolAdminsList: {
    id: 'id',
    username: 'username',
    email: 'email',
    phoneNumber: 'phone_number',
    isActive: 'is_active',
    lastLogin: 'last_login',
    createdAt: 'created_at',
    actions: 'Actions',
  },
  schoolDriversList: {
    id: 'id',
    driverUniqueId: 'driver_unique_id',
    username: 'name',
    phoneNumber: 'phone_number',
    vehicleType: 'vehicle_type',
    vehicleNumber: 'vehicle_number',
    capacity: 'vehicle_capacity',
    currentStudents: 'current_student_count',
    approvalStatus: 'approval_status',
    isAvailable: 'is_available',
    subscriptionLimit: 'max_drivers',
    actions: 'Actions',
  },
  schoolDetails: {
    id: 'id',
    name: 'name',
    email: 'email',
    phoneNumber: 'phone_number',
    approvalStatus: 'approval_status',
    isActive: 'is_active',
    actions: 'Actions',
  },
  // ── Users ──────────────────────────────────────────────
  studentsList: {
    id: 'id',
    studentName: 'student_name',
    parentName: 'parent_name',
    parentPhone: 'parent_phone',
    school: 'school_name',
    classSection: 'class',
    rollNumber: 'roll_number',
    gender: 'gender',
    isActive: 'is_active',
    createdAt: 'created_at',
    actions: 'Actions',
  },
  schoolStudentsList: {
    id: 'id',
    name: 'username',
    grade: 'grade',
    parentName: 'parent_name',
    phoneNumber: 'phone_number',
    assignedDriver: 'assigned_driver',
    actions: 'Actions',
  },
  driversList: {
    id: 'id',
    driverUniqueId: 'driver_unique_id',
    name: 'name',
    phoneNumber: 'phone_number',
    vehicleType: 'vehicle_type',
    vehicleNumber: 'vehicle_number',
    school: 'school_name',
    approvalStatus: 'approval_status',
    isAvailable: 'is_available',
    rating: 'rating',
    studentCount: 'current_student_count',
    createdAt: 'created_at',
    actions: 'Actions',
  },
  driverDocuments: {
    name: 'name',
    number: 'number',
    action: 'action',
  },
  parentsList: {
    id: 'id',
    name: 'name',
    phoneNumber: 'phone_number',
    email: 'email',
    studentCount: 'student_count',
    subscriptionStatus: 'subscription_status',
    isActive: 'is_active',
    createdAt: 'created_at',
    actions: 'Actions',
  },
  parentDetails: {
    id: 'id',
    studentName: 'student_name',
    class: 'class',
    schoolId: 'school_id',
    planName: 'plan_name',
    planType: 'plan_type',
    status: 'status',
    startDate: 'start_date',
    endDate: 'end_date',
    amount: 'amount',
    paymentType: 'payment_type',
    paymentMethod: 'payment_method',
    paymentStatus: 'payment_status',
    paymentDate: 'payment_date',
  },
  // ── Trips ──────────────────────────────────────────────
  tripsList: {
    id: 'id',
    tripDate: 'trip_date',
    tripType: 'trip_type',
    driverName: 'driver_name',
    driverUniqueId: 'driver_unique_id',
    school: 'school_name',
    tripStatus: 'trip_status',
    studentCount: 'student_count',
    startTime: 'start_time',
    endTime: 'end_time',
    totalDistance: 'total_distance',
    actions: 'Actions',
  },
  liveTracking: {
    id: 'id',
    tripId: '_id',
    tripType: 'trip_type',
    startTime: 'start_time',
    totalDistance: 'total_distance',
    actions: 'Actions',
  },
  tripDetails: {
    id: 'id',
    name: 'name',
    pickupStatus: 'pickup_status',
    dropStatus: 'drop_status',
    lat: 'lat',
    lng: 'lng',
    timestamp: 'timestamp',
  },
  // ── Assignments ────────────────────────────────────────
  schoolAssignmentsList: {
    id: 'id',
    driverName: 'driver_name',
    driverUniqueId: 'driver_unique_id',
    studentName: 'student_name',
    parentName: 'parent_name',
    classSection: 'class',
    monthlyFee: 'monthly_fee',
    assignmentStatus: 'assignment_status',
    source: 'assignment_source',
    rejectionReason: 'rejection_reason',
    assignedDate: 'assigned_date',
    startDate: 'start_date',
    actions: 'Actions',
  },
  driverStudentList: {
    id: 'id',
    driverName: 'driver_name',
    driverUniqueId: 'driver_unique_id',
    studentName: 'student_name',
    parentName: 'parent_name',
    school: 'school_name',
    monthlyFee: 'monthly_fee',
    assignmentStatus: 'assignment_status',
    source: 'assignment_source',
    assignedDate: 'assigned_date',
    actions: 'Actions',
  },
  // ── Billing ────────────────────────────────────────────
  subscriptionPlans: {
    id: 'id',
    planName: 'plan_name',
    planType: 'plan_type',
    pricingModel: 'pricing_model',
    price: 'price',
    kids: 'kids',
    isActive: 'is_active',
    createdAt: 'created_at',
    actions: 'Actions',
  },
  schoolSubscriptionPlans: {
    id: 'id',
    schoolName: 'school_name',
    planName: 'plan_name',
    planType: 'plan_type',
    subscriptionStatus: 'subscription_status',
    startDate: 'start_date',
    endDate: 'end_date',
    maxDrivers: 'max_drivers',
    maxStudents: 'max_students',
    billingContact: 'billing_contact',
    autoRenew: 'auto_renew',
  },
  parentSubscriptionsList: {
    id: 'id',
    parentName: 'parent_name',
    parentPhone: 'parent_phone',
    planName: 'plan_name',
    planType: 'plan_type',
    subscriptionStatus: 'subscription_status',
    startDate: 'start_date',
    endDate: 'end_date',
    autoRenew: 'auto_renew',
    createdAt: 'created_at',
  },
  redemptionCodesList: {
    id: 'id',
    code: 'code',
    school: 'school_name',
    studentName: 'student_name',
    studentClass: 'class',
    codeStatus: 'is_redeemed',
    redeemedBy: 'redeemed_by_name',
    redeemedAt: 'redeemed_at',
    validUntil: 'end_date',
    createdAt: 'created_at',
  },
  // ── Payments ───────────────────────────────────────────
  payments: {
    id: 'id',
    transactionId: 'transaction_id',
    parentName: 'parent_name',
    parentPhone: 'parent_phone',
    paymentType: 'payment_type',
    amount: 'amount',
    paymentMethod: 'payment_method',
    paymentStatus: 'payment_status',
    planName: 'plan_name',
    paymentDate: 'payment_date',
    actions: 'Actions',
  },
  // ── Roles ──────────────────────────────────────────────
  rolesList: {
    id: 'id',
    roleName: 'name',
    description: 'description',
    createdAt: 'created_at',
    actions: 'Actions',
  },
  // ── Audit Logs ─────────────────────────────────────────
  auditLogsList: {
    id: 'id',
    action: 'action_type',
    entityType: 'entity_type',
    entityId: 'entity_id',
    performedBy: 'performed_by',
    ipAddress: 'ip_address',
    timestamp: 'created_at',
  },
  // ── Notifications ──────────────────────────────────────
  notificationsList: {
    id: 'id',
    title: 'title',
    message: 'message',
    isRead: 'is_read',
    createdAt: 'created_at',
    actions: 'Actions',
  },
  // ── Ratings & Reviews ──────────────────────────────────
  ratingsReviewsList: {
    id: 'id',
    rating: 'rating',
    parentName: 'parent_name',
    driverName: 'driver_name',
    driverUniqueId: 'driver_unique_id',
    review: 'review_text',
    tripDate: 'trip_date',
    createdAt: 'created_at',
  },
  // ── Community ──────────────────────────────────────────
  communityList: {
    id: 'id',
    content: 'content',
    author: 'author',
    isAnonymous: 'is_anonymous',
    isVisible: 'is_visible',
    isPinned: 'is_pinned',
    createdAt: 'created_at',
    actions: 'Actions',
  },
  // ── Events ─────────────────────────────────────────────
  eventsList: {
    id: 'id',
    title: 'title',
    eventType: 'event_type',
    eventDate: 'event_date',
    audienceScope: 'audience_scope',
    requiresRsvp: 'requires_rsvp',
    actions: 'Actions',
  },
  eventRSVPsList: {
    id: 'id',
    eventTitle: 'event_title',
    parentName: 'parent_name',
    studentName: 'student_name',
    rsvpStatus: 'rsvp_status',
    respondedAt: 'responded_at',
    actions: 'Actions',
  },
  // ── Support ────────────────────────────────────────────
  supportList: {
    id: 'id',
    subject: 'subject',
    raisedBy: 'raised_by',
    phone: 'phone',
    priority: 'priority',
    status: 'ticket_status',
    assignedTo: 'assigned_to',
    createdAt: 'created_at',
    resolvedAt: 'resolved_at',
    actions: 'Actions',
  },
  // ── Ads ────────────────────────────────────────────────
  adsList: {
    id: 'id',
    title: 'title',
    adType: 'ad_type',
    targetAudience: 'target_audience',
    isActive: 'is_active',
    impressions: 'impression_count',
    clicks: 'click_count',
    actions: 'Actions',
  },
}

const headerKeys = {
  // ── Admin Portal Users ─────────────────────────────────
  adminList: {
    id: '#',
    username: 'Username',
    email: 'Email',
    phoneNumber: 'Phone',
    adminRole: 'Role',
    isActive: 'Status',
    lastLogin: 'Last Login',
    createdAt: 'Created On',
    actions: 'Actions',
  },
  // ── Schools ────────────────────────────────────────────
  schoolsList: {
    id: '#',
    schoolName: 'School Name',
    cityState: 'City / State',
    contact: 'Contact',
    email: 'Email',
    driverCount: 'Drivers',
    studentCount: 'Students',
    subscriptionStatus: 'Subscription',
    createdAt: 'Added On',
    actions: 'Actions',
  },
  schoolAdminsList: {
    id: '#',
    username: 'Username',
    email: 'Email',
    phoneNumber: 'Phone',
    isActive: 'Status',
    lastLogin: 'Last Login',
    createdAt: 'Created On',
    actions: 'Actions',
  },
  schoolDriversList: {
    id: '#',
    driverUniqueId: 'Driver ID',
    username: 'Name',
    phoneNumber: 'Phone',
    vehicleType: 'Vehicle Type',
    vehicleNumber: 'Vehicle No.',
    capacity: 'Capacity',
    currentStudents: 'Students',
    approvalStatus: 'Approval',
    isAvailable: 'Available',
    subscriptionLimit: 'Limit',
    actions: 'Actions',
  },
  schoolDetails: {
    id: '#',
    name: 'Name',
    email: 'Email',
    phoneNumber: 'Phone',
    approvalStatus: 'Approval',
    isActive: 'Status',
    actions: 'Actions',
  },
  // ── Users ──────────────────────────────────────────────
  studentsList: {
    id: '#',
    studentName: 'Student Name',
    parentName: 'Parent',
    parentPhone: 'Parent Phone',
    school: 'School',
    classSection: 'Class / Section',
    rollNumber: 'Roll No.',
    gender: 'Gender',
    isActive: 'Status',
    createdAt: 'Added On',
    actions: 'Actions',
  },
  schoolStudentsList: {
    id: '#',
    name: 'Name',
    grade: 'Grade',
    parentName: 'Parent',
    phoneNumber: 'Parent Phone',
    assignedDriver: 'Assigned Driver',
    actions: 'Actions',
  },
  driversList: {
    id: '#',
    driverUniqueId: 'Driver ID',
    name: 'Name',
    phoneNumber: 'Phone',
    vehicleType: 'Vehicle Type',
    vehicleNumber: 'Vehicle No.',
    school: 'School',
    approvalStatus: 'Approval',
    isAvailable: 'Available',
    rating: 'Rating',
    studentCount: 'Students',
    createdAt: 'Joined On',
    actions: 'Actions',
  },
  driverDocuments: {
    name: 'Name',
    number: 'Number',
    action: 'Action',
  },
  parentsList: {
    id: '#',
    name: 'Name',
    phoneNumber: 'Phone',
    email: 'Email',
    studentCount: 'Students',
    subscriptionStatus: 'Subscription',
    isActive: 'Status',
    createdAt: 'Joined On',
    actions: 'Actions',
  },
  parentDetails: {
    id: '#',
    studentName: 'Name',
    class: 'Class',
    schoolId: 'School ID',
    planName: 'Plan',
    planType: 'Type',
    status: 'Status',
    startDate: 'Start Date',
    endDate: 'End Date',
    amount: 'Amount',
    paymentType: 'Type',
    paymentMethod: 'Method',
    paymentStatus: 'Status',
    paymentDate: 'Date',
  },
  // ── Trips ──────────────────────────────────────────────
  tripsList: {
    id: '#',
    tripDate: 'Date',
    tripType: 'Type',
    driverName: 'Driver',
    driverUniqueId: 'Driver ID',
    school: 'School',
    tripStatus: 'Status',
    studentCount: 'Students',
    startTime: 'Start Time',
    endTime: 'End Time',
    totalDistance: 'Distance (km)',
    actions: 'Actions',
  },
  liveTracking: {
    id: '#',
    tripId: 'Trip ID',
    tripType: 'Type',
    startTime: 'Started At',
    totalDistance: 'Total Distance',
    actions: 'Actions',
  },
  tripDetails: {
    id: '#',
    name: 'Student Name',
    pickupStatus: 'Pickup Status',
    dropStatus: 'Drop Status',
    lat: 'Latitude',
    lng: 'Longitude',
    timestamp: 'Time',
  },
  // ── Assignments ────────────────────────────────────────
  schoolAssignmentsList: {
    id: '#',
    driverName: 'Driver',
    driverUniqueId: 'Driver ID',
    studentName: 'Student',
    parentName: 'Parent',
    classSection: 'Class',
    monthlyFee: 'Monthly Fee',
    assignmentStatus: 'Status',
    source: 'Source',
    rejectionReason: 'Rejection Reason',
    assignedDate: 'Assigned Date',
    startDate: 'Start Date',
    actions: 'Actions',
  },
  driverStudentList: {
    id: '#',
    driverName: 'Driver',
    driverUniqueId: 'Driver ID',
    studentName: 'Student',
    parentName: 'Parent',
    school: 'School',
    monthlyFee: 'Monthly Fee',
    assignmentStatus: 'Status',
    source: 'Source',
    assignedDate: 'Assigned Date',
    actions: 'Actions',
  },
  // ── Billing ────────────────────────────────────────────
  subscriptionPlans: {
    id: '#',
    planName: 'Plan Name',
    planType: 'Plan Type',
    pricingModel: 'Pricing Model',
    price: 'Price',
    kids: 'Kids',
    isActive: 'Status',
    createdAt: 'Created On',
    actions: 'Actions',
  },
  schoolSubscriptionPlans: {
    id: '#',
    schoolName: 'School',
    planName: 'Plan Name',
    planType: 'Plan Type',
    subscriptionStatus: 'Status',
    startDate: 'Start Date',
    endDate: 'End Date',
    maxDrivers: 'Max Drivers',
    maxStudents: 'Max Students',
    billingContact: 'Billing Contact',
    autoRenew: 'Auto Renew',
  },
  parentSubscriptionsList: {
    id: '#',
    parentName: 'Parent',
    parentPhone: 'Phone',
    planName: 'Plan',
    planType: 'Plan Type',
    subscriptionStatus: 'Status',
    startDate: 'Start Date',
    endDate: 'End Date',
    autoRenew: 'Auto Renew',
    createdAt: 'Created On',
  },
  redemptionCodesList: {
    id: '#',
    code: 'Code',
    school: 'School',
    studentName: 'Student',
    studentClass: 'Class',
    codeStatus: 'Status',
    redeemedBy: 'Redeemed By',
    redeemedAt: 'Redeemed At',
    validUntil: 'Valid Until',
    createdAt: 'Created On',
  },
  // ── Payments ───────────────────────────────────────────
  payments: {
    id: '#',
    transactionId: 'Transaction ID',
    parentName: 'Parent',
    parentPhone: 'Phone',
    paymentType: 'Payment Type',
    amount: 'Amount',
    paymentMethod: 'Method',
    paymentStatus: 'Status',
    planName: 'Plan',
    paymentDate: 'Date',
    actions: 'Actions',
  },
  // ── Roles ──────────────────────────────────────────────
  rolesList: {
    id: '#',
    roleName: 'Role Name',
    description: 'Description',
    createdAt: 'Created On',
    actions: 'Actions',
  },
  // ── Audit Logs ─────────────────────────────────────────
  auditLogsList: {
    id: '#',
    action: 'Action',
    entityType: 'Entity Type',
    entityId: 'Entity ID',
    performedBy: 'Performed By',
    ipAddress: 'IP Address',
    timestamp: 'Timestamp',
  },
  // ── Notifications ──────────────────────────────────────
  notificationsList: {
    id: '#',
    title: 'Title',
    message: 'Message',
    isRead: 'Read',
    createdAt: 'Date',
    actions: 'Actions',
  },
  // ── Ratings & Reviews ──────────────────────────────────
  ratingsReviewsList: {
    id: '#',
    rating: 'Rating',
    parentName: 'Parent',
    driverName: 'Driver',
    driverUniqueId: 'Driver ID',
    review: 'Review',
    tripDate: 'Trip Date',
    createdAt: 'Date',
  },
  // ── Community ──────────────────────────────────────────
  communityList: {
    id: '#',
    content: 'Post Content',
    author: 'Author',
    isAnonymous: 'Anonymous',
    isVisible: 'Visible',
    isPinned: 'Pinned',
    createdAt: 'Date',
    actions: 'Actions',
  },
  // ── Events ─────────────────────────────────────────────
  eventsList: {
    id: '#',
    title: 'Event Title',
    eventType: 'Type',
    eventDate: 'Date',
    audienceScope: 'Audience',
    requiresRsvp: 'RSVP',
    actions: 'Actions',
  },
  eventRSVPsList: {
    id: '#',
    eventTitle: 'Event',
    parentName: 'Parent',
    studentName: 'Student',
    rsvpStatus: 'Response',
    respondedAt: 'Responded At',
    actions: 'Actions',
  },
  // ── Support ────────────────────────────────────────────
  supportList: {
    id: '#',
    subject: 'Subject',
    raisedBy: 'Raised By',
    phone: 'Phone',
    priority: 'Priority',
    status: 'Status',
    assignedTo: 'Assigned To',
    createdAt: 'Created On',
    resolvedAt: 'Resolved On',
    actions: 'Actions',
  },
  // ── Ads ────────────────────────────────────────────────
  adsList: {
    id: '#',
    title: 'Title',
    adType: 'Type',
    targetAudience: 'Target Audience',
    isActive: 'Status',
    impressions: 'Impressions',
    clicks: 'Clicks',
    actions: 'Actions',
  },
}

// ── Badge Maps ─────────────────────────────────────────────────────────────

// Centralized className definitions (single source of truth for colors)
const badgeClassNames = {
  success: 'badge-green',
  warning: 'badge-yellow',
  error: 'badge-red',
  info: 'badge-blue',
  secondary: 'badge-gray',
  accent: 'badge-purple',
  highlight: 'badge-orange',
  teal: 'badge-teal',
}

// Centralized label definitions (single source of truth for labels)
const badgeLabels = {
  activate: 'Activate',
  deactivate: 'Deactivate',
  active: 'Active',
  inactive: 'Inactive',
  pending: 'Pending',
  approved: 'Approved',
  rejected: 'Rejected',
  scheduled: 'Scheduled',
  started: 'Started',
  in_progress: 'In Progress',
  completed: 'Completed',
  cancelled: 'Cancelled',
  refunded: 'Refunded',
  failed: 'Failed',
  parent_requested: 'Parent Requested',
  expired: 'Expired',
  picked_up: 'Picked Up',
  dropped: 'Dropped',
  missed: 'Missed',
  low: 'Low',
  medium: 'Medium',
  high: 'High',
  urgent: 'Urgent',
  open: 'Open',
  resolved: 'Resolved',
  closed: 'Closed',
  sports: 'Sports',
  parent_meeting: 'Parent Meeting',
  cultural: 'Cultural',
  holiday: 'Holiday',
  festival: 'Festival',
  exam: 'Exam',
  excursion: 'Excursion',
  general: 'General',
  attending: 'Attending',
  not_attending: 'Not Attending',
  maybe: 'Maybe',
  available: 'Available',
  redeemed: 'Redeemed',
  unknown: 'Unknown',
  yes: 'Yes',
  no: 'No',
  monthly: 'Monthly',
  quarterly: 'Quarterly',
  yearly: 'Yearly',
  visible: 'Visible',
  hidden: 'Hidden',
  pinned: 'Pinned',
  not_pinned: 'No',
  required: 'Required',
  not_required: 'No',
  read: 'Read',
  unread: 'Unread',
  subscription: 'Subscription',
  penalty: 'Penalty',
  card: 'Card',
  upi: 'UPI',
  netbanking: 'Net Banking',
  wallet: 'Wallet',
  cash: 'Cash',
  school_admin: 'School Admin',
  admin: 'Admin',
  superadmin: 'Super Admin',
}

// combined badge maps - single level
const badgeMaps = {
  true: { label: badgeLabels.activate, className: badgeClassNames.success },
  false: { label: badgeLabels.deactivate, className: badgeClassNames.warning },
  active: {
    label: badgeLabels.active,
    className: badgeClassNames.success,
  },
  inactive: {
    label: badgeLabels.inactive,
    className: badgeClassNames.warning,
  },
  pending: {
    label: badgeLabels.pending,
    className: badgeClassNames.warning,
  },
  approved: { label: badgeLabels.approved, className: badgeClassNames.success },
  rejected: {
    label: badgeLabels.rejected,
    className: badgeClassNames.error,
  },
  scheduled: {
    label: badgeLabels.scheduled,
    className: badgeClassNames.warning,
  },
  started: { label: badgeLabels.started, className: badgeClassNames.info },
  in_progress: {
    label: badgeLabels.in_progress,
    className: badgeClassNames.info,
  },
  completed: {
    label: badgeLabels.completed,
    className: badgeClassNames.success,
  },
  cancelled: {
    label: badgeLabels.cancelled,
    className: badgeClassNames.warning,
  },
  refunded: { label: badgeLabels.refunded, className: badgeClassNames.info },
  failed: { label: badgeLabels.failed, className: badgeClassNames.error },
  parent_requested: {
    label: badgeLabels.parent_requested,
    className: badgeClassNames.accent,
  },
  expired: { label: badgeLabels.expired, className: badgeClassNames.error },
  picked_up: {
    label: badgeLabels.picked_up,
    className: badgeClassNames.success,
  },
  dropped: { label: badgeLabels.dropped, className: badgeClassNames.success },
  missed: { label: badgeLabels.missed, className: badgeClassNames.error },
  low: { label: badgeLabels.low, className: badgeClassNames.secondary },
  medium: { label: badgeLabels.medium, className: badgeClassNames.warning },
  high: { label: badgeLabels.high, className: badgeClassNames.error },
  urgent: { label: badgeLabels.urgent, className: badgeClassNames.error },
  open: { label: badgeLabels.open, className: badgeClassNames.info },
  resolved: { label: badgeLabels.resolved, className: badgeClassNames.success },
  closed: { label: badgeLabels.closed, className: badgeClassNames.secondary },
  sports: { label: badgeLabels.sports, className: badgeClassNames.info },
  parent_meeting: {
    label: badgeLabels.parent_meeting,
    className: badgeClassNames.accent,
  },
  cultural: { label: badgeLabels.cultural, className: badgeClassNames.warning },
  holiday: { label: badgeLabels.holiday, className: badgeClassNames.success },
  festival: {
    label: badgeLabels.festival,
    className: badgeClassNames.highlight,
  },
  exam: { label: badgeLabels.exam, className: badgeClassNames.error },
  excursion: { label: badgeLabels.excursion, className: badgeClassNames.teal },
  general: { label: badgeLabels.general, className: badgeClassNames.secondary },
  attending: {
    label: badgeLabels.attending,
    className: badgeClassNames.success,
  },
  not_attending: {
    label: badgeLabels.not_attending,
    className: badgeClassNames.error,
  },
  maybe: { label: badgeLabels.maybe, className: badgeClassNames.warning },
  available: {
    label: badgeLabels.available,
    className: badgeClassNames.success,
  },
  redeemed: {
    label: badgeLabels.redeemed,
    className: badgeClassNames.secondary,
  },
  undefined: {
    label: badgeLabels.unknown,
    className: badgeClassNames.secondary,
  },
  monthly: {
    label: badgeLabels.monthly,
    className: badgeClassNames.info,
  },
  quarterly: {
    label: badgeLabels.quarterly,
    className: badgeClassNames.accent,
  },
  yearly: {
    label: badgeLabels.yearly,
    className: badgeClassNames.success,
  },
  anonymous: {
    label: badgeLabels.yes,
    className: badgeClassNames.secondary,
  },
  public: {
    label: badgeLabels.no,
    className: badgeClassNames.info,
  },
  visible: {
    label: badgeLabels.visible,
    className: badgeClassNames.success,
  },
  hidden: {
    label: badgeLabels.hidden,
    className: badgeClassNames.error,
  },
  pinned: {
    label: badgeLabels.pinned,
    className: badgeClassNames.highlight,
  },
  not_pinned: {
    label: badgeLabels.not_pinned,
    className: badgeClassNames.secondary,
  },
  required: {
    label: badgeLabels.required,
    className: badgeClassNames.info,
  },
  not_required: {
    label: badgeLabels.not_required,
    className: badgeClassNames.secondary,
  },
  read: {
    label: badgeLabels.read,
    className: badgeClassNames.secondary,
  },
  unread: {
    label: badgeLabels.unread,
    className: badgeClassNames.warning,
  },
  subscription: {
    label: badgeLabels.subscription,
    className: badgeClassNames.info,
  },
  penalty: {
    label: badgeLabels.penalty,
    className: badgeClassNames.error,
  },
  card: {
    label: badgeLabels.card,
    className: badgeClassNames.info,
  },
  upi: {
    label: badgeLabels.upi,
    className: badgeClassNames.success,
  },
  netbanking: {
    label: badgeLabels.netbanking,
    className: badgeClassNames.accent,
  },
  wallet: {
    label: badgeLabels.wallet,
    className: badgeClassNames.highlight,
  },
  cash: {
    label: badgeLabels.cash,
    className: badgeClassNames.secondary,
  },
  school_admin: {
    label: badgeLabels.school_admin,
    className: badgeClassNames.teal,
  },
  admin: {
    label: badgeLabels.admin,
    className: badgeClassNames.info,
  },
  superadmin: {
    label: badgeLabels.superadmin,
    className: badgeClassNames.accent,
  },
}

export { accessorkeys, headerKeys, badgeClassNames, badgeLabels, badgeMaps }
