export interface State {
  code: string
  name: string
}

export interface City {
  name: string
  stateCode: string
}

export const INDIAN_STATES: State[] = [
  { code: 'AP', name: 'Andhra Pradesh' },
  { code: 'AR', name: 'Arunachal Pradesh' },
  { code: 'AS', name: 'Assam' },
  { code: 'BR', name: 'Bihar' },
  { code: 'CG', name: 'Chhattisgarh' },
  { code: 'GA', name: 'Goa' },
  { code: 'GJ', name: 'Gujarat' },
  { code: 'HR', name: 'Haryana' },
  { code: 'HP', name: 'Himachal Pradesh' },
  { code: 'JH', name: 'Jharkhand' },
  { code: 'KA', name: 'Karnataka' },
  { code: 'KL', name: 'Kerala' },
  { code: 'MP', name: 'Madhya Pradesh' },
  { code: 'MH', name: 'Maharashtra' },
  { code: 'MN', name: 'Manipur' },
  { code: 'ML', name: 'Meghalaya' },
  { code: 'MZ', name: 'Mizoram' },
  { code: 'NL', name: 'Nagaland' },
  { code: 'OD', name: 'Odisha' },
  { code: 'PB', name: 'Punjab' },
  { code: 'RJ', name: 'Rajasthan' },
  { code: 'SK', name: 'Sikkim' },
  { code: 'TN', name: 'Tamil Nadu' },
  { code: 'TS', name: 'Telangana' },
  { code: 'TR', name: 'Tripura' },
  { code: 'UP', name: 'Uttar Pradesh' },
  { code: 'UK', name: 'Uttarakhand' },
  { code: 'WB', name: 'West Bengal' },
  { code: 'AN', name: 'Andaman and Nicobar Islands' },
  { code: 'CH', name: 'Chandigarh' },
  { code: 'DH', name: 'Dadra and Nagar Haveli and Daman and Diu' },
  { code: 'DL', name: 'Delhi' },
  { code: 'JK', name: 'Jammu and Kashmir' },
  { code: 'LA', name: 'Ladakh' },
  { code: 'LD', name: 'Lakshadweep' },
  { code: 'PY', name: 'Puducherry' },
]

export const INDIAN_CITIES: City[] = [
  // Andhra Pradesh (AP)
  { name: 'Visakhapatnam', stateCode: 'AP' },
  { name: 'Vijayawada', stateCode: 'AP' },
  { name: 'Guntur', stateCode: 'AP' },
  { name: 'Nellore', stateCode: 'AP' },
  { name: 'Kurnool', stateCode: 'AP' },
  { name: 'Rajahmundry', stateCode: 'AP' },
  { name: 'Tirupati', stateCode: 'AP' },
  { name: 'Kadapa', stateCode: 'AP' },
  { name: 'Anantapur', stateCode: 'AP' },
  { name: 'Kakinada', stateCode: 'AP' },
  { name: 'Vizianagaram', stateCode: 'AP' },
  { name: 'Eluru', stateCode: 'AP' },
  { name: 'Ongole', stateCode: 'AP' },
  { name: 'Nandyal', stateCode: 'AP' },
  { name: 'Machilipatnam', stateCode: 'AP' },
  { name: 'Adoni', stateCode: 'AP' },
  { name: 'Tenali', stateCode: 'AP' },
  { name: 'Proddatur', stateCode: 'AP' },
  { name: 'Chittoor', stateCode: 'AP' },
  { name: 'Hindupur', stateCode: 'AP' },
  { name: 'Bhimavaram', stateCode: 'AP' },
  { name: 'Madanapalle', stateCode: 'AP' },
  { name: 'Guntakal', stateCode: 'AP' },
  { name: 'Dharmavaram', stateCode: 'AP' },
  { name: 'Gudivada', stateCode: 'AP' },
  { name: 'Srikakulam', stateCode: 'AP' },
  { name: 'Narasaraopet', stateCode: 'AP' },
  { name: 'Tadipatri', stateCode: 'AP' },
  { name: 'Tadepalligudem', stateCode: 'AP' },
  { name: 'Chilakaluripet', stateCode: 'AP' },

  // Arunachal Pradesh (AR)
  { name: 'Itanagar', stateCode: 'AR' },
  { name: 'Naharlagun', stateCode: 'AR' },
  { name: 'Pasighat', stateCode: 'AR' },
  { name: 'Tawang', stateCode: 'AR' },
  { name: 'Bomdila', stateCode: 'AR' },
  { name: 'Ziro', stateCode: 'AR' },
  { name: 'Along', stateCode: 'AR' },
  { name: 'Tezu', stateCode: 'AR' },
  { name: 'Seppa', stateCode: 'AR' },
  { name: 'Roing', stateCode: 'AR' },

  // Assam (AS)
  { name: 'Guwahati', stateCode: 'AS' },
  { name: 'Silchar', stateCode: 'AS' },
  { name: 'Dibrugarh', stateCode: 'AS' },
  { name: 'Jorhat', stateCode: 'AS' },
  { name: 'Nagaon', stateCode: 'AS' },
  { name: 'Tinsukia', stateCode: 'AS' },
  { name: 'Tezpur', stateCode: 'AS' },
  { name: 'Bongaigaon', stateCode: 'AS' },
  { name: 'Dhubri', stateCode: 'AS' },
  { name: 'Diphu', stateCode: 'AS' },
  { name: 'Goalpara', stateCode: 'AS' },
  { name: 'Golaghat', stateCode: 'AS' },
  { name: 'Hailakandi', stateCode: 'AS' },
  { name: 'Hojai', stateCode: 'AS' },
  { name: 'Karimganj', stateCode: 'AS' },
  { name: 'Kokrajhar', stateCode: 'AS' },
  { name: 'Lakhimpur', stateCode: 'AS' },
  { name: 'Lumding', stateCode: 'AS' },
  { name: 'Mangaldoi', stateCode: 'AS' },
  { name: 'Sivasagar', stateCode: 'AS' },

  // Bihar (BR)
  { name: 'Patna', stateCode: 'BR' },
  { name: 'Gaya', stateCode: 'BR' },
  { name: 'Bhagalpur', stateCode: 'BR' },
  { name: 'Muzaffarpur', stateCode: 'BR' },
  { name: 'Darbhanga', stateCode: 'BR' },
  { name: 'Purnia', stateCode: 'BR' },
  { name: 'Bihar Sharif', stateCode: 'BR' },
  { name: 'Arrah', stateCode: 'BR' },
  { name: 'Begusarai', stateCode: 'BR' },
  { name: 'Katihar', stateCode: 'BR' },
  { name: 'Munger', stateCode: 'BR' },
  { name: 'Chhapra', stateCode: 'BR' },
  { name: 'Sasaram', stateCode: 'BR' },
  { name: 'Hajipur', stateCode: 'BR' },
  { name: 'Dehri', stateCode: 'BR' },
  { name: 'Siwan', stateCode: 'BR' },
  { name: 'Motihari', stateCode: 'BR' },
  { name: 'Nawada', stateCode: 'BR' },
  { name: 'Bagaha', stateCode: 'BR' },
  { name: 'Buxar', stateCode: 'BR' },
  { name: 'Kishanganj', stateCode: 'BR' },
  { name: 'Sitamarhi', stateCode: 'BR' },
  { name: 'Jamalpur', stateCode: 'BR' },
  { name: 'Jehanabad', stateCode: 'BR' },
  { name: 'Aurangabad', stateCode: 'BR' },

  // Chhattisgarh (CG)
  { name: 'Raipur', stateCode: 'CG' },
  { name: 'Bilaspur', stateCode: 'CG' },
  { name: 'Durg', stateCode: 'CG' },
  { name: 'Bhilai', stateCode: 'CG' },
  { name: 'Korba', stateCode: 'CG' },
  { name: 'Rajnandgaon', stateCode: 'CG' },
  { name: 'Raigarh', stateCode: 'CG' },
  { name: 'Jagdalpur', stateCode: 'CG' },
  { name: 'Ambikapur', stateCode: 'CG' },
  { name: 'Dhamtari', stateCode: 'CG' },
  { name: 'Mahasamund', stateCode: 'CG' },
  { name: 'Chirmiri', stateCode: 'CG' },
  { name: 'Bhatapara', stateCode: 'CG' },
  { name: 'Dalli-Rajhara', stateCode: 'CG' },
  { name: 'Tilda Newra', stateCode: 'CG' },

  // Goa (GA)
  { name: 'Panaji', stateCode: 'GA' },
  { name: 'Margao', stateCode: 'GA' },
  { name: 'Vasco da Gama', stateCode: 'GA' },
  { name: 'Mapusa', stateCode: 'GA' },
  { name: 'Ponda', stateCode: 'GA' },
  { name: 'Bicholim', stateCode: 'GA' },
  { name: 'Curchorem', stateCode: 'GA' },
  { name: 'Sanquelim', stateCode: 'GA' },
  { name: 'Cuncolim', stateCode: 'GA' },
  { name: 'Quepem', stateCode: 'GA' },

  // Gujarat (GJ)
  { name: 'Ahmedabad', stateCode: 'GJ' },
  { name: 'Surat', stateCode: 'GJ' },
  { name: 'Vadodara', stateCode: 'GJ' },
  { name: 'Rajkot', stateCode: 'GJ' },
  { name: 'Bhavnagar', stateCode: 'GJ' },
  { name: 'Jamnagar', stateCode: 'GJ' },
  { name: 'Junagadh', stateCode: 'GJ' },
  { name: 'Gandhinagar', stateCode: 'GJ' },
  { name: 'Anand', stateCode: 'GJ' },
  { name: 'Nadiad', stateCode: 'GJ' },
  { name: 'Navsari', stateCode: 'GJ' },
  { name: 'Morbi', stateCode: 'GJ' },
  { name: 'Surendranagar', stateCode: 'GJ' },
  { name: 'Gandhidham', stateCode: 'GJ' },
  { name: 'Vapi', stateCode: 'GJ' },
  { name: 'Bharuch', stateCode: 'GJ' },
  { name: 'Mehsana', stateCode: 'GJ' },
  { name: 'Bhuj', stateCode: 'GJ' },
  { name: 'Porbandar', stateCode: 'GJ' },
  { name: 'Palanpur', stateCode: 'GJ' },
  { name: 'Valsad', stateCode: 'GJ' },
  { name: 'Patan', stateCode: 'GJ' },
  { name: 'Veraval', stateCode: 'GJ' },
  { name: 'Godhra', stateCode: 'GJ' },
  { name: 'Bhavnagar', stateCode: 'GJ' },
  { name: 'Kalol', stateCode: 'GJ' },
  { name: 'Dahod', stateCode: 'GJ' },
  { name: 'Botad', stateCode: 'GJ' },
  { name: 'Amreli', stateCode: 'GJ' },
  { name: 'Deesa', stateCode: 'GJ' },

  // Haryana (HR)
  { name: 'Faridabad', stateCode: 'HR' },
  { name: 'Gurgaon', stateCode: 'HR' },
  { name: 'Panipat', stateCode: 'HR' },
  { name: 'Ambala', stateCode: 'HR' },
  { name: 'Yamunanagar', stateCode: 'HR' },
  { name: 'Rohtak', stateCode: 'HR' },
  { name: 'Hisar', stateCode: 'HR' },
  { name: 'Karnal', stateCode: 'HR' },
  { name: 'Sonipat', stateCode: 'HR' },
  { name: 'Panchkula', stateCode: 'HR' },
  { name: 'Bhiwani', stateCode: 'HR' },
  { name: 'Sirsa', stateCode: 'HR' },
  { name: 'Bahadurgarh', stateCode: 'HR' },
  { name: 'Jind', stateCode: 'HR' },
  { name: 'Thanesar', stateCode: 'HR' },
  { name: 'Kaithal', stateCode: 'HR' },
  { name: 'Rewari', stateCode: 'HR' },
  { name: 'Palwal', stateCode: 'HR' },
  { name: 'Hansi', stateCode: 'HR' },
  { name: 'Narnaul', stateCode: 'HR' },
  { name: 'Fatehabad', stateCode: 'HR' },
  { name: 'Gohana', stateCode: 'HR' },
  { name: 'Tohana', stateCode: 'HR' },

  // Himachal Pradesh (HP)
  { name: 'Shimla', stateCode: 'HP' },
  { name: 'Dharamshala', stateCode: 'HP' },
  { name: 'Solan', stateCode: 'HP' },
  { name: 'Mandi', stateCode: 'HP' },
  { name: 'Kullu', stateCode: 'HP' },
  { name: 'Manali', stateCode: 'HP' },
  { name: 'Hamirpur', stateCode: 'HP' },
  { name: 'Bilaspur', stateCode: 'HP' },
  { name: 'Una', stateCode: 'HP' },
  { name: 'Nahan', stateCode: 'HP' },
  { name: 'Chamba', stateCode: 'HP' },
  { name: 'Palampur', stateCode: 'HP' },
  { name: 'Sundarnagar', stateCode: 'HP' },
  { name: 'Kangra', stateCode: 'HP' },
  { name: 'Baddi', stateCode: 'HP' },

  // Jharkhand (JH)
  { name: 'Ranchi', stateCode: 'JH' },
  { name: 'Jamshedpur', stateCode: 'JH' },
  { name: 'Dhanbad', stateCode: 'JH' },
  { name: 'Bokaro', stateCode: 'JH' },
  { name: 'Deoghar', stateCode: 'JH' },
  { name: 'Hazaribagh', stateCode: 'JH' },
  { name: 'Phusro', stateCode: 'JH' },
  { name: 'Giridih', stateCode: 'JH' },
  { name: 'Ramgarh', stateCode: 'JH' },
  { name: 'Medininagar', stateCode: 'JH' },
  { name: 'Chirkunda', stateCode: 'JH' },
  { name: 'Adityapur', stateCode: 'JH' },
  { name: 'Saunda', stateCode: 'JH' },
  { name: 'Sahibganj', stateCode: 'JH' },
  { name: 'Jhumri Tilaiya', stateCode: 'JH' },
  { name: 'Pakur', stateCode: 'JH' },
  { name: 'Chaibasa', stateCode: 'JH' },
  { name: 'Dumka', stateCode: 'JH' },

  // Karnataka (KA)
  { name: 'Bangalore', stateCode: 'KA' },
  { name: 'Mysore', stateCode: 'KA' },
  { name: 'Hubli', stateCode: 'KA' },
  { name: 'Mangalore', stateCode: 'KA' },
  { name: 'Belgaum', stateCode: 'KA' },
  { name: 'Gulbarga', stateCode: 'KA' },
  { name: 'Davangere', stateCode: 'KA' },
  { name: 'Bellary', stateCode: 'KA' },
  { name: 'Tumkur', stateCode: 'KA' },
  { name: 'Shimoga', stateCode: 'KA' },
  { name: 'Bijapur', stateCode: 'KA' },
  { name: 'Raichur', stateCode: 'KA' },
  { name: 'Hospet', stateCode: 'KA' },
  { name: 'Gadag-Betageri', stateCode: 'KA' },
  { name: 'Hassan', stateCode: 'KA' },
  { name: 'Udupi', stateCode: 'KA' },
  { name: 'Robertsonpet', stateCode: 'KA' },
  { name: 'Bhadravati', stateCode: 'KA' },
  { name: 'Chitradurga', stateCode: 'KA' },
  { name: 'Kolar', stateCode: 'KA' },
  { name: 'Mandya', stateCode: 'KA' },
  { name: 'Chikmagalur', stateCode: 'KA' },
  { name: 'Gangavati', stateCode: 'KA' },
  { name: 'Bagalkot', stateCode: 'KA' },
  { name: 'Ranebennuru', stateCode: 'KA' },
  { name: 'Dharwad', stateCode: 'KA' },

  // Kerala (KL)
  { name: 'Thiruvananthapuram', stateCode: 'KL' },
  { name: 'Kochi', stateCode: 'KL' },
  { name: 'Kozhikode', stateCode: 'KL' },
  { name: 'Thrissur', stateCode: 'KL' },
  { name: 'Kannur', stateCode: 'KL' },
  { name: 'Kollam', stateCode: 'KL' },
  { name: 'Palakkad', stateCode: 'KL' },
  { name: 'Alappuzha', stateCode: 'KL' },
  { name: 'Malappuram', stateCode: 'KL' },
  { name: 'Kottayam', stateCode: 'KL' },
  { name: 'Kasaragod', stateCode: 'KL' },
  { name: 'Pathanamthitta', stateCode: 'KL' },
  { name: 'Idukki', stateCode: 'KL' },
  { name: 'Wayanad', stateCode: 'KL' },
  { name: 'Thalassery', stateCode: 'KL' },
  { name: 'Ponnani', stateCode: 'KL' },
  { name: 'Vatakara', stateCode: 'KL' },
  { name: 'Kanhangad', stateCode: 'KL' },
  { name: 'Payyanur', stateCode: 'KL' },
  { name: 'Koyilandy', stateCode: 'KL' },
  { name: 'Parappanangadi', stateCode: 'KL' },
  { name: 'Kalamassery', stateCode: 'KL' },
  { name: 'Neyyattinkara', stateCode: 'KL' },
  { name: 'Tanur', stateCode: 'KL' },
  { name: 'Kayamkulam', stateCode: 'KL' },
  { name: 'Thrippunithura', stateCode: 'KL' },
  { name: 'Angamaly', stateCode: 'KL' },
  { name: 'Perinthalmanna', stateCode: 'KL' },
  { name: 'Ottapalam', stateCode: 'KL' },
  { name: 'Tirur', stateCode: 'KL' },

  // Madhya Pradesh (MP)
  { name: 'Indore', stateCode: 'MP' },
  { name: 'Bhopal', stateCode: 'MP' },
  { name: 'Jabalpur', stateCode: 'MP' },
  { name: 'Gwalior', stateCode: 'MP' },
  { name: 'Ujjain', stateCode: 'MP' },
  { name: 'Sagar', stateCode: 'MP' },
  { name: 'Dewas', stateCode: 'MP' },
  { name: 'Satna', stateCode: 'MP' },
  { name: 'Ratlam', stateCode: 'MP' },
  { name: 'Rewa', stateCode: 'MP' },
  { name: 'Murwara', stateCode: 'MP' },
  { name: 'Singrauli', stateCode: 'MP' },
  { name: 'Burhanpur', stateCode: 'MP' },
  { name: 'Khandwa', stateCode: 'MP' },
  { name: 'Bhind', stateCode: 'MP' },
  { name: 'Chhindwara', stateCode: 'MP' },
  { name: 'Guna', stateCode: 'MP' },
  { name: 'Shivpuri', stateCode: 'MP' },
  { name: 'Vidisha', stateCode: 'MP' },
  { name: 'Chhatarpur', stateCode: 'MP' },
  { name: 'Damoh', stateCode: 'MP' },
  { name: 'Mandsaur', stateCode: 'MP' },
  { name: 'Khargone', stateCode: 'MP' },
  { name: 'Neemuch', stateCode: 'MP' },
  { name: 'Pithampur', stateCode: 'MP' },
  { name: 'Hoshangabad', stateCode: 'MP' },
  { name: 'Itarsi', stateCode: 'MP' },
  { name: 'Sehore', stateCode: 'MP' },
  { name: 'Morena', stateCode: 'MP' },
  { name: 'Betul', stateCode: 'MP' },

  // Maharashtra (MH)
  { name: 'Mumbai', stateCode: 'MH' },
  { name: 'Pune', stateCode: 'MH' },
  { name: 'Nagpur', stateCode: 'MH' },
  { name: 'Thane', stateCode: 'MH' },
  { name: 'Nashik', stateCode: 'MH' },
  { name: 'Aurangabad', stateCode: 'MH' },
  { name: 'Solapur', stateCode: 'MH' },
  { name: 'Kolhapur', stateCode: 'MH' },
  { name: 'Amravati', stateCode: 'MH' },
  { name: 'Nanded', stateCode: 'MH' },
  { name: 'Sangli', stateCode: 'MH' },
  { name: 'Jalgaon', stateCode: 'MH' },
  { name: 'Akola', stateCode: 'MH' },
  { name: 'Latur', stateCode: 'MH' },
  { name: 'Ahmednagar', stateCode: 'MH' },
  { name: 'Dhule', stateCode: 'MH' },
  { name: 'Ichalkaranji', stateCode: 'MH' },
  { name: 'Chandrapur', stateCode: 'MH' },
  { name: 'Parbhani', stateCode: 'MH' },
  { name: 'Jalna', stateCode: 'MH' },
  { name: 'Bhusawal', stateCode: 'MH' },
  { name: 'Navi Mumbai', stateCode: 'MH' },
  { name: 'Panvel', stateCode: 'MH' },
  { name: 'Satara', stateCode: 'MH' },
  { name: 'Beed', stateCode: 'MH' },
  { name: 'Yavatmal', stateCode: 'MH' },
  { name: 'Osmanabad', stateCode: 'MH' },
  { name: 'Nandurbar', stateCode: 'MH' },
  { name: 'Wardha', stateCode: 'MH' },
  { name: 'Udgir', stateCode: 'MH' },
  { name: 'Achalpur', stateCode: 'MH' },
  { name: 'Gondia', stateCode: 'MH' },
  { name: 'Barshi', stateCode: 'MH' },
  { name: 'Vasai-Virar', stateCode: 'MH' },
  { name: 'Kalyan-Dombivli', stateCode: 'MH' },
  { name: 'Ulhasnagar', stateCode: 'MH' },
  { name: 'Bid', stateCode: 'MH' },
  { name: 'Pimpri-Chinchwad', stateCode: 'MH' },
  { name: 'Malegaon', stateCode: 'MH' },
  { name: 'Ambarnath', stateCode: 'MH' },

  // Manipur (MN)
  { name: 'Imphal', stateCode: 'MN' },
  { name: 'Thoubal', stateCode: 'MN' },
  { name: 'Bishnupur', stateCode: 'MN' },
  { name: 'Churachandpur', stateCode: 'MN' },
  { name: 'Ukhrul', stateCode: 'MN' },
  { name: 'Senapati', stateCode: 'MN' },
  { name: 'Tamenglong', stateCode: 'MN' },
  { name: 'Chandel', stateCode: 'MN' },

  // Meghalaya (ML)
  { name: 'Shillong', stateCode: 'ML' },
  { name: 'Tura', stateCode: 'ML' },
  { name: 'Jowai', stateCode: 'ML' },
  { name: 'Nongstoin', stateCode: 'ML' },
  { name: 'Baghmara', stateCode: 'ML' },
  { name: 'Williamnagar', stateCode: 'ML' },
  { name: 'Resubelpara', stateCode: 'ML' },

  // Mizoram (MZ)
  { name: 'Aizawl', stateCode: 'MZ' },
  { name: 'Lunglei', stateCode: 'MZ' },
  { name: 'Champhai', stateCode: 'MZ' },
  { name: 'Serchhip', stateCode: 'MZ' },
  { name: 'Kolasib', stateCode: 'MZ' },
  { name: 'Saiha', stateCode: 'MZ' },
  { name: 'Lawngtlai', stateCode: 'MZ' },
  { name: 'Mamit', stateCode: 'MZ' },

  // Nagaland (NL)
  { name: 'Kohima', stateCode: 'NL' },
  { name: 'Dimapur', stateCode: 'NL' },
  { name: 'Mokokchung', stateCode: 'NL' },
  { name: 'Tuensang', stateCode: 'NL' },
  { name: 'Wokha', stateCode: 'NL' },
  { name: 'Zunheboto', stateCode: 'NL' },
  { name: 'Phek', stateCode: 'NL' },
  { name: 'Mon', stateCode: 'NL' },
  { name: 'Kiphire', stateCode: 'NL' },
  { name: 'Longleng', stateCode: 'NL' },
  { name: 'Peren', stateCode: 'NL' },

  // Odisha (OD)
  { name: 'Bhubaneswar', stateCode: 'OD' },
  { name: 'Cuttack', stateCode: 'OD' },
  { name: 'Rourkela', stateCode: 'OD' },
  { name: 'Berhampur', stateCode: 'OD' },
  { name: 'Sambalpur', stateCode: 'OD' },
  { name: 'Puri', stateCode: 'OD' },
  { name: 'Balasore', stateCode: 'OD' },
  { name: 'Baripada', stateCode: 'OD' },
  { name: 'Bhadrak', stateCode: 'OD' },
  { name: 'Balangir', stateCode: 'OD' },
  { name: 'Jharsuguda', stateCode: 'OD' },
  { name: 'Jeypore', stateCode: 'OD' },
  { name: 'Bargarh', stateCode: 'OD' },
  { name: 'Rayagada', stateCode: 'OD' },
  { name: 'Paradip', stateCode: 'OD' },
  { name: 'Barbil', stateCode: 'OD' },
  { name: 'Kendujhar', stateCode: 'OD' },
  { name: 'Sunabeda', stateCode: 'OD' },
  { name: 'Baleswar', stateCode: 'OD' },
  { name: 'Talcher', stateCode: 'OD' },

  // Punjab (PB)
  { name: 'Ludhiana', stateCode: 'PB' },
  { name: 'Amritsar', stateCode: 'PB' },
  { name: 'Jalandhar', stateCode: 'PB' },
  { name: 'Patiala', stateCode: 'PB' },
  { name: 'Bathinda', stateCode: 'PB' },
  { name: 'Mohali', stateCode: 'PB' },
  { name: 'Pathankot', stateCode: 'PB' },
  { name: 'Hoshiarpur', stateCode: 'PB' },
  { name: 'Batala', stateCode: 'PB' },
  { name: 'Moga', stateCode: 'PB' },
  { name: 'Malerkotla', stateCode: 'PB' },
  { name: 'Khanna', stateCode: 'PB' },
  { name: 'Phagwara', stateCode: 'PB' },
  { name: 'Muktsar', stateCode: 'PB' },
  { name: 'Barnala', stateCode: 'PB' },
  { name: 'Rajpura', stateCode: 'PB' },
  { name: 'Firozpur', stateCode: 'PB' },
  { name: 'Kapurthala', stateCode: 'PB' },
  { name: 'Faridkot', stateCode: 'PB' },
  { name: 'Sunam', stateCode: 'PB' },
  { name: 'Sangrur', stateCode: 'PB' },
  { name: 'Fazilka', stateCode: 'PB' },
  { name: 'Gurdaspur', stateCode: 'PB' },
  { name: 'Kharar', stateCode: 'PB' },
  { name: 'Gobindgarh', stateCode: 'PB' },
  { name: 'Mansa', stateCode: 'PB' },
  { name: 'Malout', stateCode: 'PB' },
  { name: 'Nabha', stateCode: 'PB' },
  { name: 'Tarn Taran', stateCode: 'PB' },
  { name: 'Jagraon', stateCode: 'PB' },

  // Rajasthan (RJ)
  { name: 'Jaipur', stateCode: 'RJ' },
  { name: 'Jodhpur', stateCode: 'RJ' },
  { name: 'Kota', stateCode: 'RJ' },
  { name: 'Bikaner', stateCode: 'RJ' },
  { name: 'Udaipur', stateCode: 'RJ' },
  { name: 'Ajmer', stateCode: 'RJ' },
  { name: 'Bhilwara', stateCode: 'RJ' },
  { name: 'Alwar', stateCode: 'RJ' },
  { name: 'Bharatpur', stateCode: 'RJ' },
  { name: 'Sikar', stateCode: 'RJ' },
  { name: 'Pali', stateCode: 'RJ' },
  { name: 'Sri Ganganagar', stateCode: 'RJ' },
  { name: 'Tonk', stateCode: 'RJ' },
  { name: 'Kishangarh', stateCode: 'RJ' },
  { name: 'Beawar', stateCode: 'RJ' },
  { name: 'Hanumangarh', stateCode: 'RJ' },
  { name: 'Baran', stateCode: 'RJ' },
  { name: 'Sawai Madhopur', stateCode: 'RJ' },
  { name: 'Churu', stateCode: 'RJ' },
  { name: 'Jhunjhunu', stateCode: 'RJ' },
  { name: 'Chittorgarh', stateCode: 'RJ' },
  { name: 'Barmer', stateCode: 'RJ' },
  { name: 'Nagaur', stateCode: 'RJ' },
  { name: 'Banswara', stateCode: 'RJ' },
  { name: 'Jhalawar', stateCode: 'RJ' },
  { name: 'Bundi', stateCode: 'RJ' },
  { name: 'Dungarpur', stateCode: 'RJ' },
  { name: 'Rajsamand', stateCode: 'RJ' },
  { name: 'Pratapgarh', stateCode: 'RJ' },
  { name: 'Mount Abu', stateCode: 'RJ' },

  // Sikkim (SK)
  { name: 'Gangtok', stateCode: 'SK' },
  { name: 'Namchi', stateCode: 'SK' },
  { name: 'Gyalshing', stateCode: 'SK' },
  { name: 'Mangan', stateCode: 'SK' },
  { name: 'Rangpo', stateCode: 'SK' },
  { name: 'Jorethang', stateCode: 'SK' },
  { name: 'Singtam', stateCode: 'SK' },
  { name: 'Naya Bazar', stateCode: 'SK' },

  // Tamil Nadu (TN)
  { name: 'Chennai', stateCode: 'TN' },
  { name: 'Coimbatore', stateCode: 'TN' },
  { name: 'Madurai', stateCode: 'TN' },
  { name: 'Tiruchirappalli', stateCode: 'TN' },
  { name: 'Salem', stateCode: 'TN' },
  { name: 'Tirunelveli', stateCode: 'TN' },
  { name: 'Tiruppur', stateCode: 'TN' },
  { name: 'Vellore', stateCode: 'TN' },
  { name: 'Erode', stateCode: 'TN' },
  { name: 'Thoothukudi', stateCode: 'TN' },
  { name: 'Thanjavur', stateCode: 'TN' },
  { name: 'Nagercoil', stateCode: 'TN' },
  { name: 'Dindigul', stateCode: 'TN' },
  { name: 'Kanchipuram', stateCode: 'TN' },
  { name: 'Karur', stateCode: 'TN' },
  { name: 'Kumbakonam', stateCode: 'TN' },
  { name: 'Hosur', stateCode: 'TN' },
  { name: 'Ambattur', stateCode: 'TN' },
  { name: 'Pudukkottai', stateCode: 'TN' },
  { name: 'Pollachi', stateCode: 'TN' },
  { name: 'Rajapalayam', stateCode: 'TN' },
  { name: 'Sivakasi', stateCode: 'TN' },
  { name: 'Cuddalore', stateCode: 'TN' },
  { name: 'Neyveli', stateCode: 'TN' },
  { name: 'Tiruvannamalai', stateCode: 'TN' },
  { name: 'Pallavaram', stateCode: 'TN' },
  { name: 'Avadi', stateCode: 'TN' },
  { name: 'Tambaram', stateCode: 'TN' },
  { name: 'Tiruvottiyur', stateCode: 'TN' },
  { name: 'Alandur', stateCode: 'TN' },
  { name: 'Kanyakumari', stateCode: 'TN' },
  { name: 'Ooty', stateCode: 'TN' },
  { name: 'Kodaikanal', stateCode: 'TN' },
  { name: 'Pondicherry', stateCode: 'TN' },

  // Telangana (TS)
  { name: 'Hyderabad', stateCode: 'TS' },
  { name: 'Warangal', stateCode: 'TS' },
  { name: 'Nizamabad', stateCode: 'TS' },
  { name: 'Karimnagar', stateCode: 'TS' },
  { name: 'Khammam', stateCode: 'TS' },
  { name: 'Ramagundam', stateCode: 'TS' },
  { name: 'Mahbubnagar', stateCode: 'TS' },
  { name: 'Nalgonda', stateCode: 'TS' },
  { name: 'Adilabad', stateCode: 'TS' },
  { name: 'Suryapet', stateCode: 'TS' },
  { name: 'Siddipet', stateCode: 'TS' },
  { name: 'Miryalaguda', stateCode: 'TS' },
  { name: 'Jagtial', stateCode: 'TS' },
  { name: 'Mancherial', stateCode: 'TS' },
  { name: 'Nirmal', stateCode: 'TS' },
  { name: 'Kamareddy', stateCode: 'TS' },
  { name: 'Bodhan', stateCode: 'TS' },
  { name: 'Palwancha', stateCode: 'TS' },
  { name: 'Kothagudem', stateCode: 'TS' },
  { name: 'Secunderabad', stateCode: 'TS' },

  // Tripura (TR)
  { name: 'Agartala', stateCode: 'TR' },
  { name: 'Udaipur', stateCode: 'TR' },
  { name: 'Dharmanagar', stateCode: 'TR' },
  { name: 'Belonia', stateCode: 'TR' },
  { name: 'Kailasahar', stateCode: 'TR' },
  { name: 'Khowai', stateCode: 'TR' },
  { name: 'Ambassa', stateCode: 'TR' },
  { name: 'Teliamura', stateCode: 'TR' },
  { name: 'Sabroom', stateCode: 'TR' },
  { name: 'Kamalpur', stateCode: 'TR' },

  // Uttar Pradesh (UP)
  { name: 'Lucknow', stateCode: 'UP' },
  { name: 'Kanpur', stateCode: 'UP' },
  { name: 'Ghaziabad', stateCode: 'UP' },
  { name: 'Agra', stateCode: 'UP' },
  { name: 'Varanasi', stateCode: 'UP' },
  { name: 'Meerut', stateCode: 'UP' },
  { name: 'Prayagraj', stateCode: 'UP' },
  { name: 'Bareilly', stateCode: 'UP' },
  { name: 'Aligarh', stateCode: 'UP' },
  { name: 'Moradabad', stateCode: 'UP' },
  { name: 'Noida', stateCode: 'UP' },
  { name: 'Gorakhpur', stateCode: 'UP' },
  { name: 'Firozabad', stateCode: 'UP' },
  { name: 'Saharanpur', stateCode: 'UP' },
  { name: 'Jhansi', stateCode: 'UP' },
  { name: 'Mathura', stateCode: 'UP' },
  { name: 'Muzaffarnagar', stateCode: 'UP' },
  { name: 'Rampur', stateCode: 'UP' },
  { name: 'Shahjahanpur', stateCode: 'UP' },
  { name: 'Farrukhabad', stateCode: 'UP' },
  { name: 'Hapur', stateCode: 'UP' },
  { name: 'Budaun', stateCode: 'UP' },
  { name: 'Sambhal', stateCode: 'UP' },
  { name: 'Hardoi', stateCode: 'UP' },
  { name: 'Raebareli', stateCode: 'UP' },
  { name: 'Etawah', stateCode: 'UP' },
  { name: 'Orai', stateCode: 'UP' },
  { name: 'Bahraich', stateCode: 'UP' },
  { name: 'Unnao', stateCode: 'UP' },
  { name: 'Rae Bareli', stateCode: 'UP' },
  { name: 'Loni', stateCode: 'UP' },
  { name: 'Sitapur', stateCode: 'UP' },
  { name: 'Bharatpur', stateCode: 'UP' },
  { name: 'Pilibhit', stateCode: 'UP' },
  { name: 'Barabanki', stateCode: 'UP' },
  { name: 'Khurja', stateCode: 'UP' },
  { name: 'Gonda', stateCode: 'UP' },
  { name: 'Mainpuri', stateCode: 'UP' },
  { name: 'Lalitpur', stateCode: 'UP' },
  { name: 'Etah', stateCode: 'UP' },
  { name: 'Deoria', stateCode: 'UP' },
  { name: 'Ghazipur', stateCode: 'UP' },
  { name: 'Sultanpur', stateCode: 'UP' },
  { name: 'Azamgarh', stateCode: 'UP' },
  { name: 'Bijnor', stateCode: 'UP' },
  { name: 'Sahaswan', stateCode: 'UP' },
  { name: 'Chandausi', stateCode: 'UP' },
  { name: 'Akbarpur', stateCode: 'UP' },
  { name: 'Ballia', stateCode: 'UP' },
  { name: 'Tanda', stateCode: 'UP' },
  { name: 'Greater Noida', stateCode: 'UP' },

  // Uttarakhand (UK)
  { name: 'Dehradun', stateCode: 'UK' },
  { name: 'Haridwar', stateCode: 'UK' },
  { name: 'Roorkee', stateCode: 'UK' },
  { name: 'Haldwani', stateCode: 'UK' },
  { name: 'Rudrapur', stateCode: 'UK' },
  { name: 'Rishikesh', stateCode: 'UK' },
  { name: 'Kashipur', stateCode: 'UK' },
  { name: 'Pithoragarh', stateCode: 'UK' },
  { name: 'Ramnagar', stateCode: 'UK' },
  { name: 'Nainital', stateCode: 'UK' },
  { name: 'Mussoorie', stateCode: 'UK' },
  { name: 'Almora', stateCode: 'UK' },
  { name: 'Tehri', stateCode: 'UK' },
  { name: 'Pauri', stateCode: 'UK' },
  { name: 'Bageshwar', stateCode: 'UK' },
  { name: 'Champawat', stateCode: 'UK' },
  { name: 'Rudraprayag', stateCode: 'UK' },
  { name: 'Uttarkashi', stateCode: 'UK' },

  // West Bengal (WB)
  { name: 'Kolkata', stateCode: 'WB' },
  { name: 'Asansol', stateCode: 'WB' },
  { name: 'Siliguri', stateCode: 'WB' },
  { name: 'Durgapur', stateCode: 'WB' },
  { name: 'Bardhaman', stateCode: 'WB' },
  { name: 'Malda', stateCode: 'WB' },
  { name: 'Baharampur', stateCode: 'WB' },
  { name: 'Habra', stateCode: 'WB' },
  { name: 'Kharagpur', stateCode: 'WB' },
  { name: 'Howrah', stateCode: 'WB' },
  { name: 'Raiganj', stateCode: 'WB' },
  { name: 'Krishnanagar', stateCode: 'WB' },
  { name: 'Darjeeling', stateCode: 'WB' },
  { name: 'Jalpaiguri', stateCode: 'WB' },
  { name: 'Balurghat', stateCode: 'WB' },
  { name: 'Basirhat', stateCode: 'WB' },
  { name: 'Medinipur', stateCode: 'WB' },
  { name: 'Haldia', stateCode: 'WB' },
  { name: 'Ranaghat', stateCode: 'WB' },
  { name: 'Bankura', stateCode: 'WB' },
  { name: 'Purulia', stateCode: 'WB' },
  { name: 'Nabadwip', stateCode: 'WB' },
  { name: 'Cooch Behar', stateCode: 'WB' },
  { name: 'Alipurduar', stateCode: 'WB' },
  { name: 'Tamluk', stateCode: 'WB' },
  { name: 'Rajarhat', stateCode: 'WB' },
  { name: 'Barrackpore', stateCode: 'WB' },
  { name: 'Bhatpara', stateCode: 'WB' },
  { name: 'Chandannagar', stateCode: 'WB' },
  { name: 'Bally', stateCode: 'WB' },

  // Andaman and Nicobar Islands (AN)
  { name: 'Port Blair', stateCode: 'AN' },

  // Chandigarh (CH)
  { name: 'Chandigarh', stateCode: 'CH' },

  // Dadra and Nagar Haveli and Daman and Diu (DH)
  { name: 'Daman', stateCode: 'DH' },
  { name: 'Diu', stateCode: 'DH' },
  { name: 'Silvassa', stateCode: 'DH' },

  // Delhi (DL)
  { name: 'New Delhi', stateCode: 'DL' },
  { name: 'Delhi', stateCode: 'DL' },

  // Jammu and Kashmir (JK)
  { name: 'Srinagar', stateCode: 'JK' },
  { name: 'Jammu', stateCode: 'JK' },
  { name: 'Anantnag', stateCode: 'JK' },

  // Ladakh (LA)
  { name: 'Leh', stateCode: 'LA' },
  { name: 'Kargil', stateCode: 'LA' },

  // Lakshadweep (LD)
  { name: 'Kavaratti', stateCode: 'LD' },

  // Puducherry (PY)
  { name: 'Puducherry', stateCode: 'PY' },
  { name: 'Karaikal', stateCode: 'PY' },
  { name: 'Yanam', stateCode: 'PY' },
  { name: 'Mahe', stateCode: 'PY' },
]

export const getCitiesByStateCode = (stateCode: string): string[] => {
  return INDIAN_CITIES.filter((city) => city.stateCode === stateCode).map(
    (city) => city.name
  )
}
